# **Qui Quadrado**

In [1]:
# Importação das funções, chi2_contingency porque temos 2 categorias
import numpy as np
from scipy.stats import chi2_contingency

In [2]:
# Crianção de matriz com os dados e execução do teste
novela = np.array([[19,6],[43,32]])
novela

array([[19,  6],
       [43, 32]])

In [4]:
# Segundo valor é o pvalor
# Valor de p é maior que 0,05 não há evidencias de diferenrença significativa (hipotese nula): não há diferença significativa
chi2_contingency(novela)

(2.037351443123939,
 0.15347667161786666,
 1,
 array([[15.5,  9.5],
        [46.5, 28.5]]))

In [5]:
# Criando uma segunda matriz
novela2 = np.array([[22, 3], [43, 32]])
novela2

array([[22,  3],
       [43, 32]])

In [6]:
# Agora valor de p menor que 0,05 podemos rejeitar a hipotese nula em favor da hipotese alternativa há diferenças significativa.
chi2_contingency(novela2)

(6.461538461538461,
 0.011023416388221425,
 1,
 array([[16.25,  8.75],
        [48.75, 26.25]]))